# Generated by Django 5.1.1 on 2024-09-29 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sokajy',
            options={'ordering': ('anarana',), 'verbose_name_plural': 'Sokajy rehetra'},
        ),
        migrations.CreateModel(
            name='Entambarotra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anarana', models.CharField(max_length=255)),
                ('fanazavana', models.TextField(blank=True, null=True)),
                ('vidiny', models.FloatField()),
                ('sary', models.ImageField(blank=True, null=True, upload_to='item_images')),
                ('lafo_ve', models.BooleanField(default=False)),
                ('daty', models.DateTimeField(auto_now_add=True)),
                ('mpivarotra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
                ('sokajy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='item.sokajy')),
            ],
        ),
    ]
