# Generated by Django 5.1.1 on 2024-09-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_sokajy_options_entambarotra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entambarotra',
            options={'ordering': ('anarana',), 'verbose_name_plural': 'Etambarotra'},
        ),
        migrations.AlterModelOptions(
            name='sokajy',
            options={'ordering': ('anarana',), 'verbose_name_plural': 'Sokajy'},
        ),
        migrations.AlterField(
            model_name='entambarotra',
            name='sary',
            field=models.ImageField(blank=True, default='item_images/default.jpg', null=True, upload_to='item_images'),
        ),
    ]
